### ISSUE TITLE
cannot compile due to undeclared identifier in nevadia_main.pas

### ISSUE THREAD

**Issue by wvaughn409** [prof-pguth/git_microdem#2]
[dcc64 Error] nevadia_main.pas(3163): E2003 Undeclared identifier: 'TestPythonFile'
[dcc64 Fatal Error] microdem.dpr(249): F2063 Could not compile used unit 'nevadia_main.pas'

**Comment by prof-pguth** [comment]
{$IfDef IncludePython}
      TestPythonFile;
   {$EndIf}


Comment out that line (or use conditional compiler directives).  It is currently not working, and not a high priority to get working.

**Comment by prof-pguth** [comment]
Since it compiles for me, and I have not heard back, I am closing the issue.
