### ISSUE TITLE
Geotiff not projected correctly

### ISSUE THREAD

**Issue by Pawel-Stankiewicz** [prof-pguth/git_microdem#3]
EDIT SUMMARY: https://github.com/prof-pguth/git_microdem/issues/3#issuecomment-1930960548

If I correctly understand the help file, the only files correctly projected are lat/long and in UTM projection. I'd like to use OSGB36 / British National Grid and LAEA with Copernicus GLO-30

**Comment by prof-pguth** [comment]
Hi,


Those should be readable, but not writeable.

If you have problems reading, I should be able to fix "easily".

Where there issues 1 and two?
     On Sunday, February 4, 2024 at 07:44:02 PM EST, Pawel-Stankiewicz ***@***.***> wrote:  
 
 


If I correctly understand the help file, the only files correctly projected are lat/long and in UTM projection. I'd like to use OSGB36 / British National Grid and LAEA with Copernicus GLO-30

**Comment by prof-pguth** [comment]
Should work correctly now if you get the new zip in the Google Drive.

**Comment by Pawel-Stankiewicz** [comment]
Now is worse, it opens without elevation data, also in tropics

**Comment by prof-pguth** [comment]
Hi,

There are several things going on.

The lack of elevations is only apparent, since the DEM is too small to create a hillshade. At least that is the case after the only issues.

The program wanted to default to a UTM projection, but not consistently, so it was working for me yesterday, and off and on until I tracked down the issue this morning.

I am working on some unrelated bugs and don't want to post a new install on microdem.org, but the install below should work for you.

https://drive.google.com/file/d/1rCyB1IMiqDajH3kgW-BboLxlQfIM-QAx/view?usp=sharing

If you are still having problems, I need to see a debug log and hopefully a bigger test DEM (I have not seen Geotiffs in the UK-OS projection that I can remember, at least at the 50 m post spacing, and I could not easily find if they were still available yesterday--with CopDEM, I would never choose them due to both the projection and lower quality).
     On Tuesday, February 6, 2024 at 04:37:01 AM EST, Pawel-Stankiewicz ***@***.***> wrote:  
 
 


Now is worse, it opens without elevation data, also in tropics

**Comment by Pawel-Stankiewicz** [comment]
What do you mean by lower quality of CopDEM? For Europe lower than what? In papers, people write about it as the best one.
British DEM, Terrain 50, uses OSGB36
Anyway, for universal projection of geotiffs I guess MicroDEM would have to use Gdal. And I guess it is not easy.

In 2020.8.20.1 version elevations were colored and its values displayed in the status bar. 
2024.2.2.4 does none of this, and calculated slope return geotiff with no data.
2024.2.6.1 display the geotiff on the right place. After Calculate/ Derivate Grid/ slope only elevation values are displayed in the status bar, and saved geotiff has no data.

Log file:
20:49:28.782 Opened Debug log: C:\md_install\microdem\logs\microdem_debug_log.txt
Log from 02.06.24
EXE: C:\md_install\microdem\microdem.exe
Build: MICRODEM 2024.2.6.1 debug version
Compiled: Delphi 11 Alexandria
DB driver: tDBF
INI: C:\Users\...

20:49:28.785 GetHardware
Windows 11 (Version 23H2, OS Build 22631.3085, 64-bit Edition)
Total Physical Memory: 19.4 Gb
AMD64 Family 23 Model 96 Stepping 1
CPU Speed: 2994 MHz
Processors: 12
Monitors: 1  Screen Resolution, Colors: 32 bits
Monitor 1: 2560x1080   96 dpi Left=0  top=0
Video card: AMD Radeon(TM) Graphics
Computer name: PAVILION15
Free disk space on C: 17.0 Gb

20:49:29.106 GotHardware
20:49:29.106  Debug file opened  handles open=302
20:49:29.106  Start LoadMDdefaults ProgramMode=0
20:49:29.128  MakeRequiredDirectories out, MainMapData=c:\mapdata\
20:49:29.129  End LoadMDdefaults ProgramMode=0
20:49:29.145  Microdem Temp Dir: c:\mapdata\temp\   Free space: 17.0 Gb
20:49:29.533  GDAL valid, C:\OSGeo4W\bin\  GDAL 3.8.3, released 2024/01/04

20:49:29.543  MDdef.AutoOpen=0  MDdef.ProgramOption=0
20:49:29.544  MDdef.AutoOpen completed, Twmdem.FormActivate wsMaximized, width=2576  & height=1066
20:49:29.545  ending FormActivate, first time
20:49:36.959  DefineProjectionParameters Loading WKT for osgb_1936
20:49:36.960  DefineProjectionParameters Loading WKT, pName=British National Grid
20:49:36.960  DefineProjectionParameters out, DEM proj=British National Grid
20:49:36.960  after define proj, SW corner x=326937.15 y=679093.43  dx=50  dy=50 m pName=British National Grid
20:49:36.961  tDEMDataSet.DefineDEMVariables in, pname=British National Grid
20:49:36.961  tDEMDataSet.DefineDEMVariables call init datum, pname=British National Grid
20:49:36.961  tDEMDataSet.DefineDEMVariables assigned projection, pname=British National Grid
20:49:36.962  tDEMDataSet.DefineDEMVariables datum init, pname=British National Grid
20:49:36.962  tDEMDataSet.DefineDEMVariables out, pname=British National Grid
20:49:36.963  After DefineDEMvariable, pName=British National Grid
20:49:37.084  Initialize TIFF DEM out, pName=British National Grid
20:49:37.085  After InitializeTiffDEM back, pname=British National Grid
20:49:37.229  Geotiff DEM CheckMaxMinElev over z range: 0 to 50  m test_dem_5x5 DEM=1 z range: 0 to 50  m
20:49:37.229  tTIFFImage.CreateDEM out, DEM=British National Grid
20:49:37.230  Load Geotiff read test_dem_5x5 DEM size: 5x5  4-byte real  z range: 0 to 50  m  Horiz: 50x50 m
20:49:37.230  test_dem_5x5 test_dem_5x5 Tiff Read British National Grid  ProjMapScale=0.9996 ellipse=OGB-M h_f=0.003341 a=6377563.4 long0=-2 lat0=49 false_east=400000 false_north=-100000
20:49:37.231  test_dem_5x5 Exit NewArea for test_dem_5x5 British National Grid  ProjMapScale=0.9996 ellipse=OGB-M h_f=0.003341 a=6377563.4 long0=-2 lat0=49 false_east=400000 false_north=-100000
20:49:39.934  SatOnMap=0   RS options=false
20:49:46.799  SatOnMap=0   RS options=false
Calculating slope
20:51:53.178  tDEMDataSet.DefineDEMVariables in, pname=Undefined
20:51:53.178  tDEMDataSet.DefineDEMVariables call init datum, pname=Undefined
20:51:53.178  tDEMDataSet.DefineDEMVariables assigned projection, pname=UTM (ellipse), zone=0N
20:51:53.179  tDEMDataSet.DefineDEMVariables datum init, pname=UTM (ellipse), zone=0N
20:51:53.179  tDEMDataSet.DefineDEMVariables out, pname=UTM (ellipse), zone=0N
20:51:58.575  ExecuteFile "C:\Program Files\Notepad++\notepad++.exe"  Parmams=C:

**Comment by prof-pguth** [comment]
I revised the previous comment, that I would CopDEM over just about anything from the UK except the 1-5 m pixel range.

I think you should test with a "big DEM", about 100 x 100 or bigger (and even that is tiny).  Many of the derived grids (like slope) won't work unless a 3x3 neighborhood is completely full.

The slope map is not correctly getting the projection; if you send a bigger DEM (or directions on where the 50 m grid can be downloaded), I can fix that.  When this gets resolved, I think the changes mean that the derived grids can be saved, as the program is using a WKT projection.  Getting it right for the (insert something like oddball or weird or maybe just small footprint) projections needs sample data, and I don't use many of them that often or keep them around from when I did several years (maybe even decades) ago.

**Comment by Pawel-Stankiewicz** [comment]
I think I will not need OSGB36, and GLO-30 uses lat/long as I checked. 
Does it mean you need to work on every projection to add support? It is very kind, thank you. I'll be glad even if I had to add a file with projection, Gdal can export .proj files QGIS also displays WKT in properties.

**Comment by prof-pguth** [comment]
Each new projection needs to have code to translate the WKT definitions into the used by MICRODEM. Mostly that is reasonably easy, but I can't do it without a concrete example that has not come up previously.

     On Tuesday, February 6, 2024 at 05:54:54 PM EST, Pawel-Stankiewicz ***@***.***> wrote:  
 
 


I think I will not need OSGB36, and GLO-30 uses lat/long as I checked.
Does it mean you need to work on every projection to add support? It is very kind, thank you. I'll be glad even if I had to add a file with projection, Gdal can export .proj files QGIS also displays WKT in properties.

**Comment by prof-pguth** [comment]
The install program at microdem.org should now be working
